spring:
  profiles: dev
  mail:
    username: ${emailId}
    password: ${emailPass}
  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?useSSL=false
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
